sudo: required
git:
  depth: 3
  submodules: false
env:
  matrix:
  #- OS_TYPE=debian OS_VERSION=9 OS_NAME=stretch
  - OS_TYPE=ubuntu OS_VERSION=18.04 OS_NAME=bionic
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get -qq update
- sudo docker pull ${OS_TYPE}:${OS_VERSION}
script:
- docker run -ti -v ${TRAVIS_BUILD_DIR}:/work:rw ${OS_TYPE}:${OS_VERSION} /bin/bash -c "cd /work; ./tests.sh ${OS_TYPE} ${OS_NAME}"
before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- dpkg-deb -b tmp newlib-hermit_2.4.0-1_amd64.deb
deploy:
  provider: bintray
  on:
    branch: hermit
    #condition: $OS_NAME = stretch
  skip_cleanup: true
  file: ".bintray_descriptor.json"
  user:
    secure: sNaHgDjLipYt3hNiVJroU4aEAQxm+3CeyFfoyID2YG0wI1bktYSQkP9g3CBjD27x3bmFyxfZrndAD7UDzI8O2xfmtbx+sLiDvXV+dgWjQLT441qkic4GtrQsLhpsYGBwk1D/D91vSiajDqE9LqBBYaaWuwMVHCXMv+SeI2VsLJTayZQ5tEzRZlichMqMneWpZpFadz1PQAp9kKX4t0VVIZHcptce1IfsM9MGpnPbPN0nn+qjYY8br3FtA3rum2Zc1cSCdAJ6CdEnYVRsVr62BhWDoeA6TDShmoKxba32wsQ5dNDDP9FYq0hBwv6HMl68d9TY+DkMvApEjri1SZXbb1rn2PgULA0dPqNZ58kSCT23us24Or6MLkYT6X5IBT5qv0pik/z5Jbgo8yvuxYwI6u+Ixfhpeducy1RBGfth9zuMmDD7nFAqCVql1Xm/u9Dcl3tKtgsYPchbQT7wK2djqkvCWnqQbGBFxm13D7X5NOCfWVT/UKAK5mf/A5/cDB4x2FVcQzq7gZkmrsDPqMQ6r/ikrGN2AmV9GTf4m2nUcuySqNcSJMsWWcBDR6GXWS3ljgy/5USgrvEVpK+BMkxb5JSM8w4fDwMxIE9Gl0QETpd8B0k1JlAPhsk6IFH5dyNRdhYDmNmhwxXaQEhM5y6q6R8jDOTT/NXIpwVOGQPhUH4=
  key:
    secure: GlgKXiBEcszLEdh5FleGbzlP5Ht1/UUXWxRIkljTANBt/ZrIZxKP5HH4e4LG/XSUXEWvbkwh8TAdKqFpYZRmvVwoDE2Hxh1KsVeYqmgg4HYY5tZk8wp0aR60UR66Pr4clT1GfOh+WMwNe0Ugh3sj5Lg1X73mUrG0ilhI89WsGqyr2uIoRKmbcUIM6wtGqoJfcqa6JgJncyUarWa/O/bxy+6xVeIREVvuX/Bfm2idtzNnAZxnwJlOP9AIiW8bBDkThzZtGSoXIPPpUu2XK7wj35px/xHn7JXKn+3XGgoENXgnym6jP9rR74KQpA3aRwNtUGF0uZrlgyzYaRCaT5HOjblj6erE+4HbXH2bRybP/G8L9chdYVsbeNzqLcrwT6zwPk+Sx9jQ/WudAcUYR3h3lnubgcSeCttdD/Z35neYEpoOBeQ69GWfjwOL8o193R1nDXK2Uwp9drxfqBySdtLtNjzpz3xG+Yi2udgJEml6W1UD1BkDeNnY8PaIdPfDbwz4Bf7AtWNul+AJcwgDB0JpDjadGeeYiCf4YKAHfODN5Sk156TEmQPEJPHmNl2hXXWLHLvpUK+QI7PCS3yRzOidvYsPuYXUVW4wUUsPuUdhsSRKTKS/JingoH7NUOH/UE1giBUppCsNqHB1v+qZkjIdcl45/NnePKzM7qBpYYBC8hg=
